project:
  type: website
  output-dir: .

website:
  title: "Andreas Jemstedt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About        
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects        
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: Journal
    toc: true

editor: visual
execute:
  engine: knitr